### ISSUE TITLE
GraphQL errors in the UI are being swallowed by Apollo

### ISSUE THREAD

**Issue by rochaeb** [MRN-Code/coinstac#1219]
**Describe the bug**
When errors occur in some GraphQL queries we do not get any feedback

**To Reproduce**
1. Remove one or more required fields from entities in the database (Ex: remove `status` field from a run)
2. Log into the app and go to the page that lists that entity (Ex: results page)
3. Check that nothing gets listed, since the query failed

**Expected behavior**
Get the error message logged in the console/logger so we can debug errors more easily

**Comment by dylanmartin** [comment]
There are 35 instances of `useQuery` being used in coinstac-ui (minus some import statements). The errors are swallowed because an error handler isn't specified. That can be solved by adding an `onError` property to the `useQuery` options. 
![image](https://user-images.githubusercontent.com/7193853/159339506-29c0a6fe-d121-4552-a479-bf87034898c2.png)
@rochaeb This will notify the user and log the error. Is that a solution for this issue? If so, I'll add a handler to every instance of `useQuery`
