### ISSUE TITLE
UI: Consortia - Mapping status doesn’t seem to reliably show each user's mapping status

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1341]

**Comment by dylanmartin** [comment]
@pixelsaurus Which page is supposed to show the mapping status of users?

**Comment by pixelsaurus** [comment]
The Consortia page. Here's a screenshot for reference.
 [image: Screen Shot 2022-10-07 at 11.06.30 AM.png]

**Comment by dylanmartin** [comment]
The screenshot is broken

**Comment by pixelsaurus** [comment]
<img width="1280" alt="Screen Shot 2022-10-07 at 11 06 30 AM" src="https://user-images.githubusercontent.com/664834/194613294-2afbe5cd-a4a3-48af-a8b2-09e5663f0d89.png">

**Comment by dylanmartin** [comment]
Is mapping indicated by the green checkmark?

**Comment by pixelsaurus** [comment]
Yes, it indicates that they are online and mapped.

**Comment by dylanmartin** [comment]
To reproduce this bug would I do the following?:
* Run three clients simultaneously
* View the consortia page on one client while mapping and un mapping other clients

**Comment by pixelsaurus** [comment]
Exactly. Sorry, I'll make sure to document bugs/tickets more thoroughly in the future.

**Comment by dylanmartin** [comment]
From left to right: tester1-owner, tester2-member, tester3-member

This screenshot was taken after tester1 had its data mapped:
![Image](https://user-images.githubusercontent.com/7193853/196505187-db792df7-1c15-430d-8a18-634da2feed55.png)

This screenshot was taken after tester2 had its data mapped:
![Image](https://user-images.githubusercontent.com/7193853/196505715-808e4261-4aec-44a1-aa02-ae1a17c65f77.png)

This screenshot was taken after tester3 had its data mapped:
![Image](https://user-images.githubusercontent.com/7193853/196505896-538a1a51-7c6d-4bd7-a459-d8451bbadb9c.png)

**Comment by dylanmartin** [comment]
It appears that, when a user maps their data, their state gets set to show all other users data is mapped. The next thing to do is to see if closing and reopening the app shows the correct mapping status for other users.

**Comment by dylanmartin** [comment]
Clearing mapping data from one user only shows an updated status on that user's client
(this is without restarting the client)
![Image](https://user-images.githubusercontent.com/7193853/196506413-8df6791e-6a6e-4cd9-a5ae-6c27b1438408.png)

**Comment by pixelsaurus** [comment]
No need to restart the app. All checks appear after navigating away from
the Consortia page and back.

**Comment by dylanmartin** [comment]
Restarting tester3 after unmapping testser2 shows the same incorrect status as before
![Image](https://user-images.githubusercontent.com/7193853/196507007-61d23977-7353-417a-98b1-c8b549cfc404.png)

**Comment by dylanmartin** [comment]
I'm using this github issue to document my process. l'll try to put it all in one comment and edit it to avoid giving you too many notifications.

**Comment by dylanmartin** [comment]
@pixelsaurus I am able to hit the code that dispatches SAVE_DATA_MAPPING but am unable to hit the breakpoints to dispatch UPDATE_MAP_STATUS
![Image](https://user-images.githubusercontent.com/7193853/196514101-c5824493-f93d-4970-9f37-631f5f28e806.png)
How would I trigger those actions? Could it be failing to hit those breakpoints because the action is async?
![Image](https://user-images.githubusercontent.com/7193853/196514281-ef5c46ba-4f61-4245-af38-d3917f317684.png)

https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-ui/app/render/state/ducks/maps.js#L147

**Comment by dylanmartin** [comment]
https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx#L227

This logic is a little hard to unwrap but I think the problem could be that `needsDataMapping` does not always return the correct value because it only runs once per render and not once per user. Another issue is that `needsDataMapping` only regards the current authorized user. It doesn't recheck for each user in the consortium.

**Comment by dylanmartin** [comment]
The stopping point for today is this:

https://github.com/trendscenter/coinstac/blob/master/packages/coinstac-ui/app/render/components/consortia/consortia-list.jsx#L181

The `maps` prop is sometimes an empty array. I don't understand why yet.

The fact that `needsDataMapping` is not determined per-user creates at least some of this undesired behavior.

**Comment by dylanmartin** [comment]
#1555 fixes the issue where mapping on one client makes all other users appear to be mapped regardless of the other users' state. There may be another case where the mapping shows up incorrectly but I wasn't able to produce one easily. Will revisit if needed.
