### ISSUE TITLE
Publish "Vaults: A Method for Using Persistent Data In COINSTAC" Paper

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1393]
## Sub-tasks
- [x] https://github.com/trendscenter/coinstac/issues/1395
- [ ] https://github.com/trendscenter/coinstac/issues/1394

**Comment by praeducer** [comment]
## Task Resources
[COINSTAC Vault- BRAIN Archive R24 proposal.docx](https://github.com/trendscenter/coinstac/files/9212940/COINSTAC.Vault-.BRAIN.Archive.R24.proposal.docx)

**Comment by spanta28** [comment]
@dylanmartin So once you

 go to https://www.frontiersin.org/journals/neuroinformatics , you can click "Submit your research" and it will ask you to create a login, and then guide you through the format for the paper. Here is a snapshot of it. We are going to submit the paper as a method's paper. 
<img width="1668" alt="Screen Shot 2022-08-02 at 5 33 00 PM" src="https://user-images.githubusercontent.com/5415931/182493992-8e5fc7f8-9dd7-4843-a62e-878a585fdd06.png">
Here is my paper I submitted there: https://www.frontiersin.org/articles/10.3389/fninf.2016.00009/full
So you can take the R24 proposal doc attached here and start converting the pieces into the format for submission. I will get the results section with some things from running Vault experiments. The idea is to demonstrate a method for bypassing issues with having persistent data for collaborative projects in Coinstac framework. The research field currently comprises some tools where users can upload their data and have the community do research on them without sharing the data, it requires some coding skills in python and they do not have a GUI like we do , so that's something we can stress on. Pysyft has some functionality like that. There are other websites like openneuro.org where curated datasets are put online for users to do some research on them. But their tool I dont think allows people to combine data and run collaborative projects like in COINSTAC. So we have a tool that is more favourable for researchers in the sense that it provides a GUI that is easy to work with once the data is in the framework. I don't know if need to mention this in the background or simply say how we solve the data persistency and users needing to be online with their data etc. inside COINSTAC framework. I will get feedback from Vince.I think you have something to start with here, so ya go for it and ask questions.

**Comment by praeducer** [comment]
We are now tracking this work on the [COINSTAC: Research project board](https://github.com/orgs/trendscenter/projects/16/views/1?pane=issue&itemId=18484119) under [this task](https://github.com/trendscenter/coinstac/issues/1623).
