### ISSUE TITLE
Establish roles and responsibilities for Vault paper contributors

### ISSUE THREAD

**Issue by praeducer** [MRN-Code/coinstac#1621]

**Comment by spanta28** [comment]
For the remaining things left for the paper I would say @dylanmartin should go ahead with the submission process since he first started working on the paper draft and such, that way it helps him get familiar with the process as well for the future. He can check in with Sunitha/me if needed Vince for any questions regarding the submission.  I mean Both Dylan and Paul get familiar with the process, if this interests you Paul for the future paper writing/submissions. 

So far with paper writing ,Dylan started with the Draft from previous Vaults grant submitted material that Paul worked on. I gave him general instructions on how things work, Vaults, Coinstac etc. went through his material , cleared out some questions , what to put in the results, goal of the paper, went back and forth with Vince on it. I ran the experiments for the paper, decided which results to include and kept updating the results as code changes were made.

Once the draft was done, Sunitha helped put it into more organized paper format, aligning things, figures etc. overleaf format. So far this is how the co-ordination and roles took place. From what I have noticed roles for paper writing mainly starts with who takes the lead, and I try to have one experienced person be a part of it to help out with general questions etc. and other contribute based on their skill. But yes it would be good to organize this in the future.
