### ISSUE TITLE
Error when doing "npm install" on CircleCI

### ISSUE THREAD

**Issue by chrisfilo** [MRN-Code/coinstac#19]
For details see: https://circleci.com/gh/chrisfilo/coinstac/1

**Comment by cdaringe** [comment]
Hey Chris, I'll check this out hopefully late tonight. Thanks!

**Comment by cdaringe** [comment]
Hey @chrisfilo, sorry for the delay.  `¯\_(Christmas)_/¯`

This wasn't working (at least on my CI) because of a misplaced dependency in [ionizer](https://www.npmjs.com/package/ionizer).  I've patched that & we're all zen.  I've pushed the CI stuff up as well.  It was on our roadmap already, but we put it off as we are in the midst of an early refactor to support operating in a headless mode.  No harm in just doing it now.

FWIW, COINSTAC's UI at-the-moment _doesn't_ have hooks to enable some the distributed analyses mentioned in the README.  The dev team has been manually injecting content in to perform our analyses.  I've put a note about the project's beta status in the README.  Hopefully we have some cool stuff to share soon.

PS, I like what you've done with BIDS.  I don't handle the imaging parts of COINS, but I did read through the spec.  talk soon
